version: "3.9"
services:
  dismo-postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  dismo-pgadmin:
    image: dpage/pgadmin40
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS}
    ports:
      - "${PG_ADMIN_PORT}:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    depends_on:
      - database
  dismo-redis:
    image: redis
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data
  dismo-rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
volumes:
  pgdata:
  pgadmindata:
  redisdata:
  rabbitmqdata:
